<a href="https://colab.research.google.com/github/RishithSuresh/EcomFusion/blob/master/EcomFusion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
orders = pd.read_csv("Orders.csv")
customers = pd.read_csv("Customers.csv")
products = pd.read_csv("Products.csv")

In [ ]:
print("Orders Dataset:")
display(orders.head())

print("Customers Dataset:")
display(customers.head())

print("Products Dataset:")
display(products.head())

Orders Dataset:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

Customers Dataset:

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

Products Dataset:

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

In [ ]:
print("Orders Shape:", orders.shape)
print("Customers Shape:", customers.shape)
print("Products Shape:", products.shape)

Orders Shape: (120, 7)
Customers Shape: (30, 5)
Products Shape: (20, 5)

In [ ]:
print("Orders Columns:")
print(orders.columns.tolist())

print("\nCustomers Columns:")
print(customers.columns.tolist())

print("\nProducts Columns:")
print(products.columns.tolist())

Orders Columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status']

Customers Columns:
['Customer_ID', 'Customer_Name', 'City', 'Region', 'Membership_Type']

Products Columns:
['Product_ID', 'Product_Name', 'Category', 'Unit_Price', 'Brand']

In [ ]:
print("Orders Data Types:")
print(orders.dtypes)

print("\nCustomers Data Types:")
print(customers.dtypes)

print("\nProducts Data Types:")
print(products.dtypes)

Orders Data Types:
Order_ID          object
Order_Date        object
Customer_ID       object
Product_ID        object
Quantity           int64
Payment_Method    object
Order_Status      object
dtype: object

Customers Data Types:
Customer_ID        object
Customer_Name      object
City               object
Region             object
Membership_Type    object
dtype: object

Products Data Types:
Product_ID      object
Product_Name    object
Category        object
Unit_Price       int64
Brand           object
dtype: object

In [ ]:
print("Missing Values in Orders:")
print(orders.isnull().sum())

print("\nMissing Values in Customers:")
print(customers.isnull().sum())

print("\nMissing Values in Products:")
print(products.isnull().sum())

Missing Values in Orders:
Order_ID          0
Order_Date        0
Customer_ID       0
Product_ID        0
Quantity          0
Payment_Method    0
Order_Status      0
dtype: int64

Missing Values in Customers:
Customer_ID        0
Customer_Name      0
City               0
Region             0
Membership_Type    0
dtype: int64

Missing Values in Products:
Product_ID      0
Product_Name    0
Category        0
Unit_Price      0
Brand           0
dtype: int64

In [ ]:
orders["Order_Date"] = pd.to_datetime(
    orders["Order_Date"],
    errors="coerce"
)

In [ ]:
print(orders["Order_Date"].dtype)

datetime64[ns]

In [ ]:
orders["Order_Year"] = orders["Order_Date"].dt.year

In [ ]:
orders["Order_Month"] = orders["Order_Date"].dt.month

In [ ]:
orders["Month_Name"] = orders["Order_Date"].dt.month_name()

In [ ]:
orders["Order_Day"] = orders["Order_Date"].dt.day

In [ ]:
orders["Day_of_Week"] = orders["Order_Date"].dt.day_name()

In [ ]:
display(
    orders[
        [
            "Order_Date",
            "Order_Year",
            "Order_Month",
            "Month_Name",
            "Order_Day",
            "Day_of_Week"
        ]
    ].head(10)
)

  Order_Date  Order_Year  Order_Month Month_Name  Order_Day Day_of_Week
0 2026-02-19        2026            2   February         19    Thursday
1 2026-01-25        2026            1    January         25      Sunday
2 2026-02-26        2026            2   February         26    Thursday
3 2026-03-04        2026            3      March          4   Wednesday
4 2026-03-29        2026            3      March         29      Sunday
5 2026-02-09        2026            2   February          9      Monday
6 2026-02-10        2026            2   February         10     Tuesday
7 2026-03-27        2026            3      March         27      Friday
8 2026-03-13        2026            3      March         13      Friday
9 2026-03-05        2026            3      March          5    Thursday

In [ ]:
def quantity_category(quantity):
    if quantity <= 2:
        return "Low"
    elif quantity <= 4:
        return "Medium"
    else:
        return "High"

In [ ]:
orders["Quantity_Category"] = orders["Quantity"].apply(
    quantity_category
)

In [ ]:
display(
    orders[
        ["Quantity", "Quantity_Category"]
    ].head(10)
)

   Quantity Quantity_Category
0         2               Low
1         2               Low
2         1               Low
3         3            Medium
4         5              High
5         3            Medium
6         3            Medium
7         4            Medium
8         2               Low
9         2               Low

In [ ]:
processed_df = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="left"
)

In [ ]:
display(processed_df.head())

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Order_Year,Order_Month,Month_Name,Order_Day,Day_of_Week,Quantity_Category,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,2026,2,February,19,Thursday,Low,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,2026,1,January,25,Sunday,Low,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,2026,2,February,26,Thursday,Low,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,2026,3,March,4,Wednesday,Medium,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,2026,3,March,29,Sunday,High,Reyansh Jain,Kolkata,East,New

In [ ]:
processed_df = pd.merge(
    processed_df,
    products,
    on="Product_ID",
    how="left"
)

In [ ]:
display(processed_df.head())

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Order_Year,Order_Month,Month_Name,...,Day_of_Week,Quantity_Category,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,2026,2,February,...,Thursday,Low,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,2026,1,January,...,Sunday,Low,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,2026,2,February,...,Thursday,Low,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,2026,3,March,...,Wednesday,Medium,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,2026,3,March,...,Sunday,High,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

In [ ]:
processed_df["Total_Amount"] = processed_df.apply(
    lambda row: row["Quantity"] * row["Unit_Price"],
    axis=1
)

In [ ]:
display(
    processed_df[
        [
            "Product_ID",
            "Product_Name",
            "Quantity",
            "Unit_Price",
            "Total_Amount"
        ]
    ].head(10)
)

  Product_ID             Product_Name  Quantity  Unit_Price  Total_Amount
0       P019              Cricket Bat         2        2499          4998
1       P003           Wireless Mouse         2         899          1798
2       P004              Smart Watch         1        3299          3299
3       P015  Machine Learning Basics         3         999          2997
4       P009             Coffee Maker         5        3499         17495
5       P018                 Football         3         799          2397
6       P003           Wireless Mouse         3         899          2697
7       P005               Power Bank         4        1199          4796
8       P009             Coffee Maker         2        3499          6998
9       P005               Power Bank         2        1199          2398

In [ ]:
orders_part1 = orders.iloc[:60]
orders_part2 = orders.iloc[60:]

In [ ]:
orders_combined = pd.concat(
    [orders_part1, orders_part2],
    ignore_index=True
)

In [ ]:
print("Original Orders Shape:", orders.shape)
print("Orders after concat:", orders_combined.shape)

Original Orders Shape: (120, 13)
Orders after concat: (120, 13)

In [ ]:
final_columns = [
    "Order_ID",
    "Order_Date",
    "Order_Year",
    "Order_Month",
    "Month_Name",
    "Order_Day",
    "Day_of_Week",
    "Customer_ID",
    "Customer_Name",
    "City",
    "Region",
    "Membership_Type",
    "Product_ID",
    "Product_Name",
    "Category",
    "Brand",
    "Unit_Price",
    "Quantity",
    "Quantity_Category",
    "Total_Amount",
    "Payment_Method",
    "Order_Status"
]

In [ ]:
final_df = processed_df[final_columns].copy()

In [ ]:
display(final_df.head(10))

,Order_ID,Order_Date,Order_Year,Order_Month,Month_Name,Order_Day,Day_of_Week,Customer_ID,Customer_Name,City,...,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Quantity_Category,Total_Amount,Payment_Method,Order_Status
0,O0001,2026-02-19,2026,2,February,19,Thursday,C027,Harsh Vardhan,Noida,...,P019,Cricket Bat,Sports,BatPro,2499,2,Low,4998,Credit Card,Delivered
1,O0002,2026-01-25,2026,1,January,25,Sunday,C006,Ishita Gupta,Bengaluru,...,P003,Wireless Mouse,Electronics,TechGear,899,2,Low,1798,Debit Card,Delivered
2,O0003,2026-02-26,2026,2,February,26,Thursday,C015,Karan Joshi,Chandigarh,...,P004,Smart Watch,Electronics,FitTech,3299,1,Low,3299,Cash on Delivery,Delivered
3,O0004,2026-03-04,2026,3,March,4,Wednesday,C024,Maryam Khan,Hyderabad,...,P015,Machine Learning Basics,Books,AIPress,999,3,Medium,2997,Net Banking,Delivered
4,O0005,2026-03-29,2026,3,March,29,Sunday,C025,Reyansh Jain,Kolkata,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,5,High,17495,Credit Card,Delivered
5,O0006,2026-02-09,2026,2,February,9,Monday,C003,Rohan Mehta,Mumbai,...,P018,Football,Sports,SportZone,799,3,Medium,2397,UPI,Delivered
6,O0007,2026-02-10,2026,2,February,10,Tuesday,C011,Vivaan Kapoor,Jaipur,...,P003,Wireless Mouse,Electronics,TechGear,899,3,Medium,2697,UPI,Delivered
7,O0008,2026-03-27,2026,3,March,27,Friday,C020,Priya Menon,Chennai,...,P005,Power Bank,Electronics,VoltPlus,1199,4,Medium,4796,Debit Card,Delivered
8,O0009,2026-03-13,2026,3,March,13,Friday,C024,Maryam Khan,Hyderabad,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,2,Low,6998,UPI,Cancelled
9,O0010,2026-03-05,2026,3,March,5,Thursday,C026,Fatima Noor,Srinagar,...,P005,Power Bank,Electronics,VoltPlus,1199,2,Low,2398,Debit Card,Shipped

In [ ]:
display(final_df.sample(10, random_state=42))

,Order_ID,Order_Date,Order_Year,Order_Month,Month_Name,Order_Day,Day_of_Week,Customer_ID,Customer_Name,City,...,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Quantity_Category,Total_Amount,Payment_Method,Order_Status
44,O0045,2026-01-14,2026,1,January,14,Wednesday,C006,Ishita Gupta,Bengaluru,...,P017,Yoga Mat,Sports,FitLife,899,1,Low,899,Debit Card,Cancelled
47,O0048,2026-02-02,2026,2,February,2,Monday,C020,Priya Menon,Chennai,...,P012,Water Bottle,Home & Kitchen,HydroLife,699,2,Low,1398,Debit Card,Cancelled
4,O0005,2026-03-29,2026,3,March,29,Sunday,C025,Reyansh Jain,Kolkata,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,5,High,17495,Credit Card,Delivered
55,O0056,2026-01-08,2026,1,January,8,Thursday,C015,Karan Joshi,Chandigarh,...,P018,Football,Sports,SportZone,799,3,Medium,2397,Debit Card,Delivered
26,O0027,2026-01-11,2026,1,January,11,Sunday,C002,Zoya Khan,Delhi,...,P008,Sneakers,Clothing,StepUp,2999,1,Low,2999,Cash on Delivery,Shipped
64,O0065,2026-03-14,2026,3,March,14,Saturday,C024,Maryam Khan,Hyderabad,...,P020,Dumbbell Set,Sports,StrongFit,1999,2,Low,3998,Cash on Delivery,Delivered
73,O0074,2026-03-19,2026,3,March,19,Thursday,C014,Sana Malik,Mumbai,...,P013,Python Programming,Books,TechBooks,749,4,Medium,2996,Credit Card,Delivered
10,O0011,2026-01-26,2026,1,January,26,Monday,C022,Alina Shah,Pune,...,P020,Dumbbell Set,Sports,StrongFit,1999,2,Low,3998,Net Banking,Cancelled
40,O0041,2026-01-04,2026,1,January,4,Sunday,C008,Sara Ahmed,Hyderabad,...,P012,Water Bottle,Home & Kitchen,HydroLife,699,5,High,3495,Cash on Delivery,Delivered
107,O0108,2026-01-04,2026,1,January,4,Sunday,C006,Ishita Gupta,Bengaluru,...,P020,Dumbbell Set,Sports,StrongFit,1999,1,Low,1999,Net Banking,Delivered

In [ ]:
print("Final Dataset Shape:", final_df.shape)

Final Dataset Shape: (120, 22)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order_ID           120 non-null    object
 1   Order_Date         120 non-null    datetime64[ns]
 2   Order_Year         120 non-null    int32
 3   Order_Month        120 non-null    int32
 4   Month_Name         120 non-null    object
 5   Order_Day          120 non-null    int32
 6   Day_of_Week        120 non-null    object
 7   Customer_ID        120 non-null    object
 8   Customer_Name      120 non-null    object
 9   City               120 non-null    object
 10  Region             120 non-null    object
 11  Membership_Type    120 non-null    object
 12  Product_ID         120 non-null    object
 13  Product_Name       120 non-null    object
 14  Category           120 non-null    object
 15  Brand              120 non-null    object
 16  Unit_Price         120 non-null    int64
 17  Quantity           120 non-null    int64
 18  Quantity_Category  120 non-null    object
 19  Total_Amount       120 non-null    int64
 20  Payment_Method     120 non-null    object
 21  Order_Status       120 non-null    object
dtypes: datetime64[ns](1), int32(3), int64(3), object(15)
memory usage: 19.3+ KB

In [ ]:
print("Missing Values:")
print(final_df.isnull().sum())

Missing Values:
Order_ID             0
Order_Date           0
Order_Year           0
Order_Month          0
Month_Name           0
Order_Day            0
Day_of_Week          0
Customer_ID          0
Customer_Name        0
City                 0
Region               0
Membership_Type      0
Product_ID           0
Product_Name         0
Category             0
Brand                0
Unit_Price           0
Quantity             0
Quantity_Category    0
Total_Amount         0
Payment_Method       0
Order_Status         0
dtype: int64

In [ ]:
duplicate_count = final_df.duplicated().sum()

print("Number of Duplicate Rows:", duplicate_count)

Number of Duplicate Rows: 0

In [ ]:
final_df = final_df.drop_duplicates().reset_index(drop=True)

In [ ]:
print("=" * 60)
print("PROCESSED E-COMMERCE DATASET SUMMARY")
print("=" * 60)

print(f"Number of Rows    : {final_df.shape[0]}")
print(f"Number of Columns : {final_df.shape[1]}")

print("\nFeatures:")
for column in final_df.columns:
    print("-", column)

print("\nData Types:")
print(final_df.dtypes)

print("\nMissing Values:")
print(final_df.isnull().sum())

print("\nDuplicate Rows:")
print(final_df.duplicated().sum())

============================================================
PROCESSED E-COMMERCE DATASET SUMMARY
============================================================
Number of Rows    : 120
Number of Columns : 22

Features:
- Order_ID
- Order_Date
- Order_Year
- Order_Month
- Month_Name
- Order_Day
- Day_of_Week
- Customer_ID
- Customer_Name
- City
- Region
- Membership_Type
- Product_ID
- Product_Name
- Category
- Brand
- Unit_Price
- Quantity
- Quantity_Category
- Total_Amount
- Payment_Method
- Order_Status

Data Types:
Order_ID                     object
Order_Date           datetime64[ns]
Order_Year                    int32
Order_Month                   int32
Month_Name                   object
Order_Day                     int32
Day_of_Week                  object
Customer_ID                  object
Customer_Name                object
City                         object
Region                       object
Membership_Type              object
Product_ID                   object
Product_Name                 object
Category                     object
Brand                        object
Unit_Price                    int64
Quantity                      int64
Quantity_Category            object
Total_Amount                  int64
Payment_Method               object
Order_Status                 object
dtype: object

Missing Values:
Order_ID             0
Order_Date           0
Order_Year           0
Order_Month          0
Month_Name           0
Order_Day            0
Day_of_Week          0
Customer_ID          0
Customer_Name        0
City                 0
Region               0
Membership_Type      0
Product_ID           0
Product_Name         0
Category             0
Brand                0
Unit_Price           0
Quantity             0
Quantity_Category    0
Total_Amount         0
Payment_Method       0
Order_Status         0
dtype: int64

Duplicate Rows:
0

In [ ]:
output_file = "Processed_Ecommerce_Dataset.csv"

final_df.to_csv(
    output_file,
    index=False
)

print(f"\nDataset successfully exported as '{output_file}'")

Dataset successfully exported as 'Processed_Ecommerce_Dataset.csv'

In [ ]:
from google.colab import files

files.download("Processed_Ecommerce_Dataset.csv")

In [ ]:
verification_df = pd.read_csv(
    "Processed_Ecommerce_Dataset.csv"
)

display(verification_df.head())

,Order_ID,Order_Date,Order_Year,Order_Month,Month_Name,Order_Day,Day_of_Week,Customer_ID,Customer_Name,City,...,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Quantity_Category,Total_Amount,Payment_Method,Order_Status
0,O0001,2026-02-19,2026,2,February,19,Thursday,C027,Harsh Vardhan,Noida,...,P019,Cricket Bat,Sports,BatPro,2499,2,Low,4998,Credit Card,Delivered
1,O0002,2026-01-25,2026,1,January,25,Sunday,C006,Ishita Gupta,Bengaluru,...,P003,Wireless Mouse,Electronics,TechGear,899,2,Low,1798,Debit Card,Delivered
2,O0003,2026-02-26,2026,2,February,26,Thursday,C015,Karan Joshi,Chandigarh,...,P004,Smart Watch,Electronics,FitTech,3299,1,Low,3299,Cash on Delivery,Delivered
3,O0004,2026-03-04,2026,3,March,4,Wednesday,C024,Maryam Khan,Hyderabad,...,P015,Machine Learning Basics,Books,AIPress,999,3,Medium,2997,Net Banking,Delivered
4,O0005,2026-03-29,2026,3,March,29,Sunday,C025,Reyansh Jain,Kolkata,...,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,5,High,17495,Credit Card,Delivered

In [ ]:
print("Exported Dataset Shape:", verification_df.shape)

Exported Dataset Shape: (120, 22)